### ISSUE TITLE
Null value in the model´s accesor example

### ISSUE THREAD

**Issue by Albvadi** [DirectoryTree/LdapRecord-Docs#10]
Hi, 
in the [Models: Accessors & Mutators](https://ldaprecord.com/docs/core/v2/model-mutators/#defining-an-accessor) on the docs, there are an error in the example of the accessor.

The `getThumbnailphotoAttribute` method begins with the following line:
```php
if ($data = base64_decode($value[0], $strict = true)) {
```
With this line, you're taking for granted the the value retrieved from AD is Base64 encoded, but don´t.
The result of that it´s false and the accessor return null.

I have not created a PR because I understand that it´s just an example and that it´s the developer's responsibility to develop the accessor correctly, but you may want to correct the example to be correct.

For my accessor, I simply use a piece of code of your old releases, that works correctly:
```php
public function getThumbnailphotoAttribute($value)
{
    if (isset($value)){
        $data = ($value) ? $value[0]:null;
    } else {
        $data = file_get_contents('images/default_photo.png');
    }

    if ($data) {
        $mime = 'image/jpeg';

        $image = base64_encode($data);

        if (function_exists('finfo_open')) {
            $finfo = finfo_open();

            $mime = finfo_buffer($finfo, $data, FILEINFO_MIME_TYPE);

            return "data:$mime;base64,$image";
        }

        return "data:$mime;base64,$image";
    }
}
```

As always, thank you so much for this wonderful project!

**Comment by stevebauman** [comment]
Awesome, great catch @Albvadi! Thanks for posting this. I'll update the docs and close this issue once it's been pushed 😄
