### ISSUE TITLE
Incorrect command for attaching a group to a user

### ISSUE THREAD

**Issue by satyakresna** [DirectoryTree/LdapRecord-Docs#19]
Hi @stevebauman, I find incorrect command for attaching group to a user in https://ldaprecord.com/docs/core/v2/model-relationships/#attaching. I think it should be: `$user->groups()->attach($user);`.

Here's the screenshot.

![gambar](https://user-images.githubusercontent.com/11099186/128658052-d626eb20-6150-499b-83c1-cfaa5da6240d.png)

**Comment by stevebauman** [comment]
Fixed, thanks for letting me know @satyakresna!

**Comment by satyakresna** [comment]
You’re welcome Steve.
