### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by salim114** [DirectoryTree/LdapRecord-Docs#35]
When we try to install Ldaprecord-laravel and type this ''composer require directorytree/ldaprecord-laravel'' that`s what we get ;

![ldap](https://user-images.githubusercontent.com/43864609/207424010-543a1666-4905-428b-a2e5-bb17cf61b4f2.png)

To counter that i use the plan B and download it "with all dependecies (-w)" like this ; ''composer require directorytree/ldaprecord-laravel -w''

please see that here : https://www.loom.com/share/99e7610b1b054b2787fb25066d621c03

Best regards.

**Comment by stevebauman** [comment]
Hi @salim114,

Please see this issue for a resolution: https://github.com/DirectoryTree/LdapRecord-Laravel/issues/392
