### ISSUE TITLE
Several documentation links on ldaprecord.com are broken.

### ISSUE THREAD

**Issue by elkbullwinkle** [DirectoryTree/LdapRecord-Docs#6]
Hi,

There are currently several links broken.
The Laravel documentation link on the index page (top right corner) does not include version and returns a 403.
Also _edit this page_ github link here https://ldaprecord.com/docs/laravel/v1/ returns a 404, looks like it's missing a slash.

Sorry, if this is a wrong repository to file this issue, it looked this one is the best match. :)

**Comment by stevebauman** [comment]
Hi @elkbullwinkle, thanks for the heads up!

I've just fixed this, all the links are good now. Appreciate it! 👍
