### ISSUE TITLE
Using my own model for ldap

### ISSUE THREAD

**Issue by yeong0809** [DirectoryTree/LdapRecord-Docs#64]
I am having the following error when implement my own model for the authentication by following the documentation in portal.

Is there anyone have any solution on it?

**Error:**
Class App\Ldap\User does not implement abstract methods: function getAuthIdentifier()
'App\Ldap\User' does not implement method 'getAuthIdentifier'

**Code:**
```
namespace App\Ldap;

use LdapRecord\Models\Model;
use LdapRecord\Models\Concerns\CanAuthenticate;
use Illuminate\Contracts\Auth\Authenticatable;

class User extends Model implements Authenticatable
{
    use CanAuthenticate;

    public static array $objectClasses = ['...'];

    protected string $guidKey = 'uuid';
}
```

**Documentation reference:** 
https://ldaprecord.com/docs/laravel/v3/auth/plain/configuration/#using-your-own-model

**Comment by stevebauman** [comment]
Hi @yeong0809,

This has been patched, thanks for the report!
