### ISSUE TITLE
[Feature] LdapRecord v3, Laravel 11, Jetstream and Fortify setup update

### ISSUE THREAD

**Issue by danito** [DirectoryTree/LdapRecord-Docs#67]
Hi,
If I'm not wrong, with Laravel 11, the app/Providers/AuthServiceProvider.php isn't use anymore.

In https://ldaprecord.com/docs/laravel/v3/auth/database/laravel-jetstream the part that explains how to override Fortify's authentication callback using the Fortify::authenticateUsing() method seems obsolete and would need an update.

**Comment by stevebauman** [comment]
Fixed!
